version: "3.1"

services:
    postgres:
        container_name: postgres
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: fullstack-tutorial
            POSTGRES_PASSWORD: fullstack-tutorial
            POSTGRES_DB: fullstack-tutorial
        ports:
            - 5432:5432

    redis:
        container_name: redis
        image: redis:alpine
        restart: always
        ports:
            - 6379:6379
